name: Exemplo Artifact
     run-name:Exemplo workflow para actifact, executado por
on:
 workflow_dispatch:

jobs: 
    upload-artifact: 
         runs-on: ubuntu-latest
         steps:
              - name: Listagem de arquivos
                run: ls                                                             //Somente para listar se tem algum arquivo
              
              - name: Gerar alguns arquivos 
                run: |
                   mkdir artefatos                                                  //Criou a pasta ARTEFATOS
                   echo "Arquivo de teste 01" > ./artefatos/primeiro_arquivo.txt
                   echo "Arquivo de teste 02" > ./artefatos/segundo_arquivo.txt
                   echo "Arquivo de teste 03" > ./artefatos/terceiro_arquivo.txt
                   echo "Arquivo de teste 04" > ./artefatos/quarta_arquivo.txt
               
              - name: envio dos arquivos
                uses: actions/upload-artifact@v4
                id: upload-artifact                                                  //Criação de ID para enviar o artafact com ID.
                with:
                  name: teste-artefato
                  path: ./artefatos
              
              - name: Listagem de arquivo
                run: ls

              - name: Endereço para Obeter os artefatos
                run: |
                 echo "${{ steps.upload-artificat.outputs.artifact-url }}"         //gerou URL para Artifact    
