name: Exemplo Artifact
run-name: Exemplo workflow para artifact, executado por ${{ github.actor }}

on: 
  workflow_dispatch:

env:
  nome-artefato: teste-artefato

jobs: 
  upload-artifact: 
    runs-on: ubuntu-latest
    steps:
      - name: Listagem de arquivos
        run: ls

      - name: Gerar arquivos de teste
        run: |
          mkdir -p artefatos
          echo "Arquivo de teste 01" > ./artefatos/primeiro_arquivo.txt
          echo "Arquivo de teste 02" > ./artefatos/segundo_arquivo.txt
          echo "Arquivo de teste 03" > ./artefatos/terceiro_arquivo.txt
          echo "Arquivo de teste 04" > ./artefatos/quarta_arquivo.txt

      - name: Envio dos arquivos
        uses: actions/upload-artifact@v4
        id: upload-artifact
        with:
          name: ${{ env.nome-artefato }}
          path: ./artefatos

      - name: Listagem pós-upload
        run: ls

      - name: Exibir URL do artifact
        run: echo "${{ steps.upload-artifact.outputs.download-url }}"

  download-artifact:
    runs-on: ubuntu-latest
    needs: [upload-artifact]
    steps:
      - name: Listagem inicial
        run: ls

      - name: Download do artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.nome-artefato }}

      - name: Listagem pós-download
        run: ls